Name=input("Enter your name")
Mail=input("Enter your mail")
Mobile=int(input("Enter your Mobile Number"))
Bank_name=input("Enter your bank name")
IFSC_code=input("Enter your bank IFSC code")
Available_balance=int(input("Enter your Available balance"))
print(Name)
print(Mail)
print(Mobile)
print(Bank_name)
print(IFSC_code)
print(Available_balance)
