Name=input("Enter your name")
Father_name=input("Enter your father name")
Mother_name=input("Enter your mother name")
Sister_name=input("Enter your sister name")
Brother_name=input("Enter your brother name")
Grandfather_name=input("Enter your granpa name")
Grandma_name=input("Enter your grandma name")
print(Name)
print(Father_name)
print(Mother_name)
print(Sister_name)
print(Brother_name)
print(Grandfather_name)
print(Grandma_name)
    
